# Generated by Django 5.2.7 on 2025-10-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=200)),
                ("property_price", models.FloatField()),
                ("property_rent", models.FloatField()),
                ("emi", models.FloatField()),
                ("tax", models.FloatField()),
                ("other_exp", models.FloatField()),
            ],
        ),
    ]
