# Generated by Django 5.2.7 on 2025-10-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="monthly_expenses",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="data",
            name="monthly_income",
            field=models.FloatField(default=0),
        ),
    ]
